#!/bin/bash

local_path=`cd $(dirname $0); pwd`
export WEBDESKIT_HOME=${local_path}/webdeskit-local/html/webdeskit.html
export WEBDESKIT_PATH=${local_path}/webdeskit-local
export WEBDESKIT_DESKTOP_PATH=$HOME/.links
export LD_LIBRARY_PATH="${local_path}/webdeskit-local/:${LD_LIBRARY_PATH}"

WD=`cd $(dirname $0); pwd`
LOCK_DIR="/tmp/.webdeskit.lock"

while ! mkdir $LOCK_DIR 2>/dev/null; do
    while [ ! -e $LOCK_DIR/pid -a -d $LOCK_DIR ]; do sleep .5; done
    _PID=`cat $LOCK_DIR/pid 2>/dev/null`
    [ -n "$_PID" ] && kill $_PID 2>/dev/null
done

if [ "$1" = "exit" ]; then rmdir ${LOCK_DIR}; exit 0; fi

(
    ${local_path}/webdeskit-local/webdeskit-main &
    _PID=$!
    echo $_PID > $LOCK_DIR/pid
    trap 'rm -rf "$LOCK_DIR"' 0
    wait $_PID 2>/dev/null
) &
