#!/bin/bash

local_path=`cd $(dirname $0); pwd`
export WEBDESKIT_HOME=${local_path}/webdeskit-local/html/webdeskit.html
export WEBDESKIT_PATH=${local_path}/webdeskit-local
export WEBDESKIT_DESKTOP_PATH=$HOME/.links
export LD_LIBRARY_PATH="${local_path}/webdeskit-local/:${LD_LIBRARY_PATH}"

exec ${local_path}/webdeskit-local/webdeskit-main
